//set values for state to be used

export default {
   
    token: null,
    providerInfo: [],
    serviceInfo: [],
    providerServiceInfo: [],
    adminProviderServiceInfo: [],
    allUserInfo: [],
    userById: "",
    createUserInfo: "",
    updateUserInfo: "",
    deleteUserInfo: "",
    linkUserProvider: [],
    resetPassword: "",
    disableUserAccount: "",
    addProviderInfo: "",
    updateProviderInfo: [],
    deleteProviderInfo: "",
    linkProviderService: "",
    addServicesOffered: "",
    updateServicesOfferedInfo: "",
    deleteServicesOffered: "",
    addBedTransaction: "",
    getBedTransaction: [],
    getAllBedTransactionsById: [],
    getProviderUsersInfo: [],
    getProviderUsersById: [],
    linkProviderUser: "",
}